version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
        - "4201:80"
        - "4200:443"
    depends_on:
        - database
  
  database:
     image: "mcr.microsoft.com/mssql/server:2022-latest"
     environment:
        SA_PASSWORD: "Rm17Op12"
        ACCEPT_EULA: "Y"
     ports:
        - "1433:1433"